# run: conda update conda
# run: conda update --all
# run: conda env create -f environment.yml
# run: source activate TDT4265
# to see list of all installed packages after activating env, run: conda list
# to search for a package on conda, run: conda search <package>
# (optional add, "-c conda-forge" for searching on community channels)

name: TDT4265
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - matplotlib
  - jupyter
  - jupyterlab
  - scikit-learn
  - scipy
  - numpy
  - pathlib
  - pandas
  - requests
  - python-dotenv
  - qgrid
  - pip
  - progressbar
  - pytorch=1.3
# for installing with pip:
#  - pip:
#    - <package>
