MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'baseline1'
        PRETRAINED: False
        INPUT_CHANNELS: 3
        OUT_CHANNELS: [512, 1024, 512, 256, 256, 256]
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    OPT: 'Adam'
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 0.0005
OUTPUT_DIR: 'outputs/rdd2020'
DATASET_DIR: "/work/datasets"