MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnext'
        PRETRAINED: True
        INPUT_CHANNELS: 3
        OUT_CHANNELS: [ 512, 1024, 2048, 2048, 512, 512 ]
    PRIORS:
      FEATURE_MAPS: [[38,38], [19,19], [10,10], [5,5], [3,3], [2,2]]
INPUT:
    IMAGE_SIZE: [300, 300]
    PIXEL_MEAN: [0.485, 0.456, 0.406]
    PIXEL_STD: [0.229, 0.224, 0.225]
DATA_AUGMENTATION:
    RANDOMCROP: False
    INVERT: False
    MIRROR: False
    COLORJITTER: False
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    OPT: 'SGD'
    MAX_ITER: 80000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 0.001
OUTPUT_DIR: 'outputs/resnext1'
DATASET_DIR: "/work/datasets"