MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'mobilenetv3'
        PRETRAINED: True
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[20,20], [10,10], [5,5], [3,3], [2,2], [1,1]]
        STRIDES: [[16,16], [32,32], [64,64], [107,107], [160,160], [320,320]]
        MIN_SIZES: [ [ 60,60 ], [ 105,105 ], [ 150,150 ], [ 195,195 ], [ 240,240 ], [ 285,285 ] ]
        MAX_SIZES: [ [ 105,105 ], [ 150,150 ], [ 195,195 ], [ 240,240 ], [ 285,285 ], [ 330,330 ] ]
        ASPECT_RATIOS: [ [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ] ]
        BOXES_PER_LOCATION: [ 6, 6, 6, 6, 6, 6 ]

INPUT:
    IMAGE_SIZE: [600, 600]
    PIXEL_MEAN: [0.485, 0.456, 0.406]
    PIXEL_STD: [0.229, 0.224, 0.225]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    OPT: 'Adam'
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 0.0005
OUTPUT_DIR: 'outputs/rdd2020'
DATASET_DIR: "datasets"