MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnext'
        PRETRAINED: True
        INPUT_CHANNELS: 3
        OUT_CHANNELS: [ 512, 1024, 2048, 512, 512, 128 ]
        DROPOUT: 0.2
    PRIORS:
      FEATURE_MAPS: [[60, 34], [30, 17], [15,9], [8,5], [4,3], [1,1]]
      STRIDES: [[8, 8], [16, 16], [32, 30], [60, 54], [120, 90], [480, 270]]
      MIN_SIZES: [[48, 27], [96, 54], [178, 100], [260, 146], [340, 192], [422, 238]]
      MAX_SIZES: [[96, 54], [178, 100], [260, 146], [340, 192], [422, 238], [504, 284]]
      ASPECT_RATIOS: [ [ 2 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2 ], [ 2 ] ]
      BOXES_PER_LOCATION: [ 4, 6, 6, 6, 4, 4 ]
INPUT:
    IMAGE_SIZE: [480, 270]
    PIXEL_MEAN: [0.485, 0.456, 0.406]
    PIXEL_STD: [0.229, 0.224, 0.225]
DATA_AUGMENTATION:
    RANDOMCROP: True
    INVERT: False
    MIRROR: True
    COLORJITTER: True
    RATIOCROP: True
DATASETS:
    TRAIN: ("rdd2020_train_oversampling",)
    TEST: ("rdd2020_val", )
SOLVER:
    OPT: 'SGD'
    MAX_ITER: 40000
    GAMMA: 0.1
    BATCH_SIZE: 32
    LR: 0.01
    LR_MIN: 0.0001
    STEP_SIZE: 1000
    LR_SCHEDULER: 'ExpCyclicLR'
OUTPUT_DIR: '/content/drive/MyDrive/Deep Learning und Computer Vision - Group 5 - Final Project/outputs/resnext_480x270_ExpCyclic'
DATASET_DIR: 'datasets'
EVAL_STEP: 2000
MODEL_SAVE_STEP: 2000
DATA_LOADER:
    NUM_WORKERS: 4
